# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b531a0d89aa855621d658232c496a413690945223b05859bd7bf6b9b2e178feb74f81dedafe7a1bad69eee630159358346eede4fbcdf7809137aae2cc041179

test:
  secret_key_base: 73d592afb5ea1989a23917b319cc9b08ef7387753b18d1528f6bf97358f6d9fa806ac8a1e2f7a62f06194ecc73b8b2c825c5e8cb90629cd38f18f6708f72843d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
